### ISSUE TITLE
SYSTEM_CONFIGURATION_AUTH_MODE=aad not working

### ISSUE THREAD

**Issue by tehSMK** [BurningOKR/BurningOKR#116]
**Describe the bug**
when changeing SYSTEM_CONFIGURATION_AUTH_MODE from local to aad in the backend.env, the backen fails to start
```
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
[2022-01-13 10:53:00.627] [ERROR] [org.springframework.boot.diagnostics.LoggingFailureAnalysisReporter] -

***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 1 of constructor in org.burningokr.service.initialisation.InitService required a bean of type 'org.burningokr.service.userhandling.UserService' that could not be found.


Action:

Consider defining a bean of type 'org.burningokr.service.userhandling.UserService' in your configuration.
```

**To Reproduce**
1. change SYSTEM_CONFIGURATION_AUTH_MODE to aad
2. run docker-compose up -d
3. run docker logs -f burning-okr-backend

**Expected behavior**
Backend starts 

**Additional context**
changeing the setting back to local the application works just fine.

**Comment by EcCo18** [comment]
Hello, thanks for submitting your problem. Can you send us your modified application.yaml? Before sending please remove  your credentials and other security parameters.

**Comment by tehSMK** [comment]
Thx for the help,

unfortunatly it doesnt work. I got a different message now. I guess the backend.env is missing something:

Error-Message:
```
***************************
APPLICATION FAILED TO START
***************************

Description:

Binding to target org.springframework.boot.autoconfigure.security.oauth2.resource.ResourceServerProperties@3bec2275 failed:

    Property: resourceServerProperties.tokenInfoUri
    Value: null
    Reason: Missing tokenInfoUri and userInfoUri and there is no JWT verifier key


Action:

Update your application's configuration
```

And here is our backen.env config: Its straight out of the repository (cleaned though):

```
##########################################################
#                                                                                                                #
# Configuration for the Docker Container of the backend. #
#                                                                                                                #
##########################################################

# The spring profile to use. "prod" is recommended.
SPRING_PROFILES_ACTIVE=prod

# The URL of the Postgres Database.
#
# When using the default Postgres Docker Container, use the URL
# jdbc:postgresql://burning-okr-postgres:5432/<database>?useSSL=false
#
# When using a Postgres database on the host machine, you can use the URL
# jdbc:postgresql://host.docker.internal:5432/<database>?useSSL=false
#
# Otherwise use the following URL Scheme to point to a database at a custom location:
# jdbc:postgresql://<hostname>:<port>/<database>?useSSL=false
SPRING_DATASOURCE_URL=jdbc:postgresql://okr-db:5432/okr?useSSL=false

# The username of the Postgres User of the OKR Tool. Should be the same as in the postgres.env.
SPRING_DATASOURCE_USERNAME=postgres

# The password of the Postgres User of the OKR Tool. Should be the same as in the postgres.env.
SPRING_DATASOURCE_PASSWORD=

# The SQL Dialect used by the backend
SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect

# SMTP Server Configuration
SPRING_MAIL_USERNAME=
SPRING_MAIL_PASSWORD=
SPRING_MAIL_HOST=
SPRING_MAIL_PORT=

# The Authentication Mode.
# Use "local" to use the local database for the user management.
# Use "aad" to use an Azure Active Directory with OAuth for the user management.
#SYSTEM_CONFIGURATION_AUTH_MODE=local
SYSTEM_CONFIGURATION_AUTH_MODE=azure

# The following settings are only for the authentication with the Azure Active Directory.
# You do not need to change anything in the following settings, when you are using the local Authentication Mode.
#
# Azure Ad Issuer
AZURE_AD_ISSUER=

# The Azure Ad ClientId
SECURITY_OAUTH2_CLIENT_CLIENTID=

# The Azure Ad Client secret
SECURITY_OAUTH2_CLIENT_CLIENTSECRET=

# The Azure Ad Access Token URI
SECURITY_OAUTH2_CLIENT_ACCESSTOKENURI=

# The Azure Ad User Authorization URI
SECURITY_OAUTH2_CLIENT_USERAUTHORIZATIONURI=

# The Azure Ad User Info URI (e.g. https://graph.microsoft.com/v1.0/me/)
SECURITY_OAUTH2_RESOURCE_USERINFOURI=

# The Azure Active Directory groups, that are authorized to use BurningOKR.
# You can add as many groups as you like.
# You must specify at least one group.
AZURE_AD_AZUREGROUPS[0]_NAME=
AZURE_AD_AZUREGROUPS[0]_ID=
# AZURE_AD_AZUREGROUPS[1]_NAME=<second-azure-group-name>
# AZURE_AD_AZUREGROUPS[1]_ID=<second-azure-group-id>
# ...
```

**Comment by MeepMr** [comment]
Hey, is it possible, that you forgot to populate the value in line 62 (SECURITY_OAUTH2_RESOURCE_USERINFOURI) after clearing the .env file to send it to us?

Also to avoid another problem, you will need to replace lines 67 and 68 with the following:

AZURE_AD_AZUREGROUPS_0_NAME=
AZURE_AD_AZUREGROUPS_0_ID=

**Comment by tehSMK** [comment]
How embarrassing. :O Yes, this was an oversight on my part.

I still get an error message while starting the application:
```
[2022-01-18 11:15:46.780] [ERROR] [org.springframework.boot.SpringApplication] - Application run failed
java.lang.IllegalStateException: STATE 403
        at org.burningokr.service.userutil.AzureApiCaller.callApi(AzureApiCaller.java:46) ~[burning-okr-logic.jar!/:?]
        at org.burningokr.service.userutil.AzureUserFetcher.fetchAzureUsersForGroupId(AzureUserFetcher.java:68) ~[burning-okr-logic.jar!/:?]
        at org.burningokr.service.userutil.AzureUserFetcher.fetchAzureUsers(AzureUserFetcher.java:57) ~[burning-okr-logic.jar!/:?]
        at org.burningokr.service.userutil.AadUserListUpdater.updateAadUserList(AadUserListUpdater.java:57) ~[burning-okr-logic.jar!/:?]
        at org.burningokr.service.userhandling.AadUserService.updateUsers(AadUserService.java:94) ~[burning-okr-logic.jar!/:?]
        at org.burningokr.service.userhandling.AadUserService.updateUsersAtStartup(AadUserService.java:88) ~[burning-okr-logic.jar!/:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_312]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_312]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_312]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_312]
        at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:261) ~[spring-context-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
        at org.springframework.context.event.ApplicationListenerMethodAdapter.processEvent(ApplicationListenerMethodAdapter.java:180) ~[spring-context-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
        at org.springframework.context.event.ApplicationListenerMethodAdapter.onApplicationEvent(ApplicationListenerMethodAdapter.java:142) ~[spring-context-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172) ~[spring-context-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165) ~[spring-context-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139) ~[spring-context-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:400) ~[spring-context-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:354) ~[spring-context-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
        at org.springframework.boot.context.event.EventPublishingRunListener.running(EventPublishingRunListener.java:103) ~[spring-boot-2.0.4.RELEASE.jar!/:2.0.4.RELEASE]
        at org.springframework.boot.SpringApplicationRunListeners.running(SpringApplicationRunListeners.java:78) ~[spring-boot-2.0.4.RELEASE.jar!/:2.0.4.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:346) [spring-boot-2.0.4.RELEASE.jar!/:2.0.4.RELEASE]
        at org.burningokr.BurningOkrApp.main(BurningOkrApp.java:33) [classes!/:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_312]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_312]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_312]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_312]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [burning-okr.jar:?]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [burning-okr.jar:?]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [burning-okr.jar:?]
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51) [burning-okr.jar:?]
```

But i guess this is because of wrong configured AAD Values on our part.

Thx for the help! Much appreciated. I'll consider this issue as solved.
