### ISSUE TITLE
Trouble getting AzureAD Login to work

### ISSUE THREAD

**Issue by tehSMK** [BurningOKR/BurningOKR#121]
**Describe the bug**
Sorry to get back on this topic once more. But i struggle to get AzureAD login working for me. Is there any more detailed information on how to configure the azureAD Login?
For example which backend.env settings corresponds to the setting in the App-Manifest in AzureAD. Or maybe how do i enable debug log to see why i get the error message below.
Is it something you can support me here? Would be great. Thx in advance.

**To Reproduce**
1. set SYSTEM_CONFIGURATION_AUTH_MODE=azure
2. fill out all AzureAD settings accordingly
3. run docker-compose up -d
4. see error

Error Message in the backend-Log:
```
burning-okr-backend | [2022-01-20 10:52:23.828] [INFO] [org.burningokr.service.cycle.CycleService] - {0}: Application startup detected, processing automatic cycle switch if necessary.
burning-okr-backend | [2022-01-20 10:52:23.884] [INFO] [org.burningokr.service.userutil.AadUserListUpdater] - Updating user database...
burning-okr-backend | [2022-01-20 10:52:26.181] [ERROR] [org.springframework.boot.SpringApplication] - Application run failed
burning-okr-backend | java.lang.IllegalStateException: STATE 403
burning-okr-backend |   at org.burningokr.service.userutil.AzureApiCaller.callApi(AzureApiCaller.java:46) ~[burning-okr-logic.jar!/:?]
burning-okr-backend |   at org.burningokr.service.userutil.AzureUserFetcher.fetchAzureUsersForGroupId(AzureUserFetcher.java:68) ~[burning-okr-logic.jar!/:?]
burning-okr-backend |   at org.burningokr.service.userutil.AzureUserFetcher.fetchAzureUsers(AzureUserFetcher.java:57) ~[burning-okr-logic.jar!/:?]
burning-okr-backend |   at org.burningokr.service.userutil.AadUserListUpdater.updateAadUserList(AadUserListUpdater.java:57) ~[burning-okr-logic.jar!/:?]
burning-okr-backend |   at org.burningokr.service.userhandling.AadUserService.updateUsers(AadUserService.java:94) ~[burning-okr-logic.jar!/:?]
burning-okr-backend |   at org.burningokr.service.userhandling.AadUserService.updateUsersAtStartup(AadUserService.java:88) ~[burning-okr-logic.jar!/:?]
burning-okr-backend |   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_312]
burning-okr-backend |   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_312]
burning-okr-backend |   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_312]
burning-okr-backend |   at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_312]
burning-okr-backend |   at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:261) ~[spring-context-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
burning-okr-backend |   at org.springframework.context.event.ApplicationListenerMethodAdapter.processEvent(ApplicationListenerMethodAdapter.java:180) ~[spring-context-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
burning-okr-backend |   at org.springframework.context.event.ApplicationListenerMethodAdapter.onApplicationEvent(ApplicationListenerMethodAdapter.java:142) ~[spring-context-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
burning-okr-backend |   at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172) ~[spring-context-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
burning-okr-backend |   at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165) ~[spring-context-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
burning-okr-backend |   at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139) ~[spring-context-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
burning-okr-backend |   at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:400) ~[spring-context-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
burning-okr-backend |   at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:354) ~[spring-context-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
burning-okr-backend |   at org.springframework.boot.context.event.EventPublishingRunListener.running(EventPublishingRunListener.java:103) ~[spring-boot-2.0.4.RELEASE.jar!/:2.0.4.RELEASE]
burning-okr-backend |   at org.springframework.boot.SpringApplicationRunListeners.running(SpringApplicationRunListeners.java:78) ~[spring-boot-2.0.4.RELEASE.jar!/:2.0.4.RELEASE]
burning-okr-backend |   at org.springframework.boot.SpringApplication.run(SpringApplication.java:346) [spring-boot-2.0.4.RELEASE.jar!/:2.0.4.RELEASE]
burning-okr-backend |   at org.burningokr.BurningOkrApp.main(BurningOkrApp.java:33) [classes!/:?]
burning-okr-backend |   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_312]
burning-okr-backend |   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_312]
burning-okr-backend |   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_312]
burning-okr-backend |   at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_312]
burning-okr-backend |   at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [burning-okr.jar:?]
burning-okr-backend |   at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [burning-okr.jar:?]
burning-okr-backend |   at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [burning-okr.jar:?]
burning-okr-backend |   at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51) [burning-okr.jar:?]
```

**Expected behavior**
Login to Application with AzureAD Login

EDIT:
Content of backend.env
```
# The Authentication Mode.
# Use "local" to use the local database for the user management.
# Use "aad" to use an Azure Active Directory with OAuth for the user management.
SYSTEM_CONFIGURATION_AUTH_MODE=azure

# The following settings are only for the authentication with the Azure Active Directory.
# You do not need to change anything in the following settings, when you are using the local Authentication Mode.
#
# Azure Ad Issuer
AZURE_AD_ISSUER=https://login.microsoftonline.com/<our_uuid>/v2.0

# The Azure Ad ClientId
SECURITY_OAUTH2_CLIENT_CLIENTID=<our_clientid>

# The Azure Ad Client secret
SECURITY_OAUTH2_CLIENT_CLIENTSECRET=<our_app_secret>

# The Azure Ad Access Token URI
SECURITY_OAUTH2_CLIENT_ACCESSTOKENURI=https://login.microsoftonline.com/<our_uuid>/oauth2/v2.0/token

# The Azure Ad User Authorization URI
SECURITY_OAUTH2_CLIENT_USERAUTHORIZATIONURI=https://login.microsoftonline.com/<our_uuid>/oauth2/v2.0/authorize

# The Azure Ad User Info URI (e.g. https://graph.microsoft.com/v1.0/me/)
SECURITY_OAUTH2_RESOURCE_USERINFOURI=https://graph.microsoft.com

# The Azure Active Directory groups, that are authorized to use BurningOKR.
# You can add as many groups as you like.
# You must specify at least one group.
AZURE_AD_AZUREGROUPS_0_NAME=<our_group_name>
AZURE_AD_AZUREGROUPS_0_ID=<our_group_uuid>

# AZURE_AD_AZUREGROUPS_1_NAME=<second-azure-group-name>
# AZURE_AD_AZUREGROUPS_1_ID=<second-azure-group-id>
# ...
```

**Comment by MeepMr** [comment]
Sorry for having you waiting for so long.

From the Log you published, it seems like one of the three credential is wrong
- appId
- the app secret
- the client id

Personally i dont have much experience with the app-manifest in Azure AD, so i dont know what the entries are named in the manifest. But from what i found out, using the microsoft docs, the following manifest should map to our configuration in the following way (using the attributes <our_uuid>, <our_app_secret> and <our_clientId> from the backend.env you provided:

- appId (not the object id from the directory) -> <our_clientId>
- the client secret shown once at the secret creation -> <our_app_secret>

The token and authorization URIs can be copied from the endpoint pane (OAUTH 2.0 TOKEN ENDPOINT and OAUTH 2.0 AUTHORIZATION ENDPOINT) found at Defalut Directory / App registrations / Endpoints

I hope, i could help you.

**Comment by MeepMr** [comment]
In the overwiew of the app, you should see some kay-data presented like the following screenshot:

![aad configuration](https://user-images.githubusercontent.com/67143880/152141201-b68372a5-8d9b-4a93-977a-8a12da639944.png)

Here the Anwendungs-ID (Client) would map to <our_clientId>
And Verzeichnis-ID (Mandat) would map to <our_uuid>

The secret will only be displayed on creation.

**Comment by tehSMK** [comment]
Thx @MeepMr for getting back on this topic. I double checked the settings. From you comment it seems pretty straight forward. I also re-created the SECRET just in case. Unfortunatly without any luck.

To top it all off when i change the setting back from "azure" to "local" all 3 container start without problem, but as soon as i enter the URL in the browser the AAD Auth kicks in and tries to log me. Without success though. Its redirecting back and forth between MS Login and OKR.

I deeply appreciate your help so far. If you have any more ideas how i can further debug it, i gladly take it. :D

Best regards,
Karsten

**Comment by MeepMr** [comment]
The tool saves the credentials and informations about the authorization mode inside the database.
This is why the weird redirect stuff is happening, when you change your auth-mode to local.

It might be worth to delete the docker volume of the postgres-db, so our tool cannot access the cached / saved informations

**Comment by MeepMr** [comment]
Hey, just checking back into this issue. Did the reset of the database help with your issue?

**Comment by tehSMK** [comment]
Sorry for the late response. A deletion of the docker volume worked as expected. Thx for your support.
