### ISSUE TITLE
Issue with Deployment using Windows and Tomcat

### ISSUE THREAD

**Issue by mzhukovs** [BurningOKR/BurningOKR#17]
This is a really great project and would love to give it a spin to help our small group try out OKRs and have some open source software to help us actually manage/track them.

I just followed the instructions to deploy with Tomcat on Windows, ensured each step was done correctly but I get this error when clicking "Start" for the /api I get the following error message - any ideas? Would really appreciate the support.

`
FAIL - Application at context path [/api] could not be started FAIL - Encountered exception [org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/api]]]
`

**Comment by mzhukovs** [comment]
Detailed Log output:

20-Feb-2021 17:13:32.284 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version name:   Apache Tomcat/9.0.43
20-Feb-2021 17:13:32.284 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server built:          Jan 28 2021 20:25:45 UTC
20-Feb-2021 17:13:32.284 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version number: 9.0.43.0
20-Feb-2021 17:13:32.284 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Name:               Windows Server 2019
20-Feb-2021 17:13:32.284 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Version:            10.0
20-Feb-2021 17:13:32.284 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Architecture:          amd64
20-Feb-2021 17:13:32.284 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Java Home:             C:\Program Files\Java\jre1.8.0_281
20-Feb-2021 17:13:32.284 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Version:           1.8.0_281-b09
20-Feb-2021 17:13:32.284 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Vendor:            Oracle Corporation
20-Feb-2021 17:13:32.284 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_BASE:         C:\Program Files\Apache Software Foundation\Tomcat 9.0
20-Feb-2021 17:13:32.284 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_HOME:         C:\Program Files\Apache Software Foundation\Tomcat 9.0
20-Feb-2021 17:13:32.284 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.home=C:\Program Files\Apache Software Foundation\Tomcat 9.0
20-Feb-2021 17:13:32.284 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.base=C:\Program Files\Apache Software Foundation\Tomcat 9.0
20-Feb-2021 17:13:32.284 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.io.tmpdir=C:\Program Files\Apache Software Foundation\Tomcat 9.0\temp
20-Feb-2021 17:13:32.284 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
20-Feb-2021 17:13:32.284 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.config.file=C:\Program Files\Apache Software Foundation\Tomcat 9.0\conf\logging.properties
20-Feb-2021 17:13:32.284 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: exit
20-Feb-2021 17:13:32.284 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: abort
20-Feb-2021 17:13:32.284 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Xms128m
20-Feb-2021 17:13:32.284 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Xmx256m
20-Feb-2021 17:13:32.300 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent The Apache Tomcat Native library which allows using OpenSSL was not found on the java.library.path: [C:\Program Files\Apache Software Foundation\Tomcat 9.0\bin;C:\windows\Sun\Java\bin;C:\windows\system32;C:\windows;C:\Program Files\Java\jre1.8.0_281\bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files\docker;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\windows\System32\OpenSSH\;E:\BMC\CTMAGENT\Control-M Agent\Default\exe;C:\ProgramData\chocolatey\bin;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files\Puppet Labs\Puppet\bin;C:\Program Files\dotnet\;C:\php;C:\Program Files (x86)\dotnet\;C:\xampp\composer;C:\util\antiword;C:\Program Files (x86)\Odoo 13.0\PostgreSQL\bin;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\docker;C:\windows\ServiceProfiles\LocalService\AppData\Local\Microsoft\WindowsApps;.]
20-Feb-2021 17:13:32.833 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-nio-8080"]
20-Feb-2021 17:13:33.129 INFO [main] org.apache.catalina.startup.Catalina.load Server initialization in [1129] milliseconds
20-Feb-2021 17:13:33.161 INFO [main] org.apache.catalina.core.StandardService.startInternal Starting service [Catalina]
20-Feb-2021 17:13:33.161 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet engine: [Apache Tomcat/9.0.43]
20-Feb-2021 17:13:33.176 INFO [main] org.apache.catalina.startup.HostConfig.deployWAR Deploying web application archive [C:\Program Files\Apache Software Foundation\Tomcat 9.0\webapps\api.war]
20-Feb-2021 17:13:42.500 INFO [main] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
20-Feb-2021 17:13:51.530 SEVERE [main] org.apache.catalina.startup.HostConfig.deployWAR Error deploying web application archive [C:\Program Files\Apache Software Foundation\Tomcat 9.0\webapps\api.war]
	java.lang.IllegalStateException: Error starting child
		at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:720)
		at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:690)
		at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:706)
		at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:946)
		at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1792)
		at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
		at java.util.concurrent.FutureTask.run(Unknown Source)
		at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
		at java.util.concurrent.AbstractExecutorService.submit(Unknown Source)
		at org.apache.catalina.startup.HostConfig.deployWARs(HostConfig.java:757)
		at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:426)
		at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1520)
		at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:309)
		at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
		at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:423)
		at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:366)
		at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:936)
		at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:843)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1384)
		at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1374)
		at java.util.concurrent.FutureTask.run(Unknown Source)
		at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
		at java.util.concurrent.AbstractExecutorService.submit(Unknown Source)
		at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:909)
		at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:262)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		at org.apache.catalina.core.StandardService.startInternal(StandardService.java:434)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:930)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		at org.apache.catalina.startup.Catalina.start(Catalina.java:772)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
		at java.lang.reflect.Method.invoke(Unknown Source)
		at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:342)
		at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:473)
	Caused by: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/api]]
		at org.apache.catalina.util.LifecycleBase.handleSubClassException(LifecycleBase.java:440)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:198)
		at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:717)
		... 37 more
	Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flywayInitializer' defined in class path resource [org/burningokr/config/MigrationConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.autoconfigure.flyway.FlywayMigrationInitializer]: Factory method 'flywayInitializer' threw exception; nested exception is org.flywaydb.core.api.FlywayException: Found more than one migration with version 1
Offenders:
-> C:\Program Files\Apache Software Foundation\Tomcat 9.0\webapps\api\WEB-INF\classes\db\migration\sqlserver\V1__Initial.sql (SQL)
-> C:\Program Files\Apache Software Foundation\Tomcat 9.0\webapps\api\WEB-INF\classes\db\migration\postgresql\V1__Initial.sql (SQL)
		at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:590)
		at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1247)
		at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1096)
		at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:535)
		at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:495)
		at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:317)
		at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
		at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:315)
		at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
		at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:304)
		at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
		at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1089)
		at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:859)
		at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)
		at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140)
		at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:762)
		at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:398)
		at org.springframework.boot.SpringApplication.run(SpringApplication.java:330)
		at org.springframework.boot.web.servlet.support.SpringBootServletInitializer.run(SpringBootServletInitializer.java:157)
		at org.springframework.boot.web.servlet.support.SpringBootServletInitializer.createRootApplicationContext(SpringBootServletInitializer.java:137)
		at org.springframework.boot.web.servlet.support.SpringBootServletInitializer.onStartup(SpringBootServletInitializer.java:91)
		at org.springframework.web.SpringServletContainerInitializer.onStartup(SpringServletContainerInitializer.java:172)
		at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5166)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		... 38 more
	Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.autoconfigure.flyway.FlywayMigrationInitializer]: Factory method 'flywayInitializer' threw exception; nested exception is org.flywaydb.core.api.FlywayException: Found more than one migration with version 1
Offenders:
-> C:\Program Files\Apache Software Foundation\Tomcat 9.0\webapps\api\WEB-INF\classes\db\migration\sqlserver\V1__Initial.sql (SQL)
-> C:\Program Files\Apache Software Foundation\Tomcat 9.0\webapps\api\WEB-INF\classes\db\migration\postgresql\V1__Initial.sql (SQL)
		at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
		at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:582)
		... 61 more
	Caused by: org.flywaydb.core.api.FlywayException: Found more than one migration with version 1
Offenders:
-> C:\Program Files\Apache Software Foundation\Tomcat 9.0\webapps\api\WEB-INF\classes\db\migration\sqlserver\V1__Initial.sql (SQL)
-> C:\Program Files\Apache Software Foundation\Tomcat 9.0\webapps\api\WEB-INF\classes\db\migration\postgresql\V1__Initial.sql (SQL)
		at org.flywaydb.core.internal.resolver.CompositeMigrationResolver.checkForIncompatibilities(CompositeMigrationResolver.java:141)
		at org.flywaydb.core.internal.resolver.CompositeMigrationResolver.doFindAvailableMigrations(CompositeMigrationResolver.java:107)
		at org.flywaydb.core.internal.resolver.CompositeMigrationResolver.resolveMigrations(CompositeMigrationResolver.java:90)
		at org.flywaydb.core.internal.resolver.CompositeMigrationResolver.resolveMigrations(CompositeMigrationResolver.java:43)
		at org.flywaydb.core.internal.info.MigrationInfoServiceImpl.refresh(MigrationInfoServiceImpl.java:114)
		at org.flywaydb.core.internal.command.DbInfo.info(DbInfo.java:68)
		at org.flywaydb.core.Flyway$4.execute(Flyway.java:1328)
		at org.flywaydb.core.Flyway$4.execute(Flyway.java:1321)
		at org.flywaydb.core.Flyway.execute(Flyway.java:1655)
		at org.flywaydb.core.Flyway.info(Flyway.java:1321)
		at org.burningokr.config.MigrationConfiguration.safeRepairDatabase(MigrationConfiguration.java:45)
		at org.burningokr.config.MigrationConfiguration.flywayInitializer(MigrationConfiguration.java:32)
		at org.burningokr.config.MigrationConfiguration$$EnhancerBySpringCGLIB$$72c45f03.CGLIB$flywayInitializer$0(<generated>)
		at org.burningokr.config.MigrationConfiguration$$EnhancerBySpringCGLIB$$72c45f03$$FastClassBySpringCGLIB$$8a3ec0c6.invoke(<generated>)
		at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
		at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:361)
		at org.burningokr.config.MigrationConfiguration$$EnhancerBySpringCGLIB$$72c45f03.flywayInitializer(<generated>)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
		at java.lang.reflect.Method.invoke(Unknown Source)
		at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
		... 62 more
20-Feb-2021 17:13:51.530 INFO [main] org.apache.catalina.startup.HostConfig.deployWAR Deployment of web application archive [C:\Program Files\Apache Software Foundation\Tomcat 9.0\webapps\api.war] has finished in [18,354] ms
20-Feb-2021 17:13:51.530 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [C:\Program Files\Apache Software Foundation\Tomcat 9.0\webapps\docs]
20-Feb-2021 17:13:51.733 INFO [main] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
20-Feb-2021 17:13:51.765 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [C:\Program Files\Apache Software Foundation\Tomcat 9.0\webapps\docs] has finished in [235] ms
20-Feb-2021 17:13:51.765 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [C:\Program Files\Apache Software Foundation\Tomcat 9.0\webapps\manager]
20-Feb-2021 17:13:51.969 INFO [main] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
20-Feb-2021 17:13:52.032 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [C:\Program Files\Apache Software Foundation\Tomcat 9.0\webapps\manager] has finished in [267] ms
20-Feb-2021 17:13:52.032 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [C:\Program Files\Apache Software Foundation\Tomcat 9.0\webapps\ROOT]
20-Feb-2021 17:13:52.219 INFO [main] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
20-Feb-2021 17:13:52.219 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [C:\Program Files\Apache Software Foundation\Tomcat 9.0\webapps\ROOT] has finished in [187] ms
20-Feb-2021 17:13:52.235 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8080"]
20-Feb-2021 17:13:52.251 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in [19121] milliseconds
20-Feb-2021 17:13:55.426 SEVERE [http-nio-8080-exec-4] org.apache.catalina.loader.WebappClassLoaderBase.checkThreadLocalMapForLeaks The web application [api] created a ThreadLocal with key of type [org.springframework.boot.SpringBootExceptionHandler.LoggedExceptionHandlerThreadLocal] (value [org.springframework.boot.SpringBootExceptionHandler$LoggedExceptionHandlerThreadLocal@24f461e4]) and a value of type [org.springframework.boot.SpringBootExceptionHandler] (value [org.springframework.boot.SpringBootExceptionHandler@69a9977f]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
20-Feb-2021 17:14:03.158 INFO [http-nio-8080-exec-4] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.

**Comment by mzhukovs** [comment]
Issue was the migrations folder had "sqlserver" folder in it that was causing problems - deleted that folder and kept the postgres one and it was able to succeed afterward.

**Comment by dustin-schlueter** [comment]
Hello mzhukovs,

nice to see, that our product fits well to your needs!
Thank you for the issue report. Just to clarify: With your workaround you can run BurningOKR without problems, correct?

Of course we will have a look to the issue and fix it or update the documentation.

With kind regards,
the BurningOKR Team

**Comment by mzhukovs** [comment]
@dustin-schlueter Yes that's right, it was just because there were 2 folders with migrations. Deleted the "sqlserver" folder and was able to deploy and run just fine.
