### ISSUE TITLE
Azure AD integration not working (Application run failed java.lang.IllegalStateException: STATE 403)

### ISSUE THREAD

**Issue by Michael-List** [BurningOKR/BurningOKR#185]
**Describe the bug**
Can't figure out how to make Azure AD integration. I'm using version 1.4.3 of Bruning OKR in docker containers.

**To Reproduce**
1. Set the following variable in backend.env file: `SYSTEM_CONFIGURATION_AUTH_MODE=azure`
2. Fill out all Azure AD settings
3. run docker-compose up -d
4. See error from backend docker container:

```
[2022-10-17 12:21:18.395] [INFO] [org.springframework.boot.web.embedded.tomcat.TomcatWebServer] - Tomcat started on port(s): 8080 (http) with context path ''
[2022-10-17 12:21:18.400] [INFO] [org.burningokr.BurningOkrApp] - Started BurningOkrApp in 15.125 seconds (JVM running for 16.899)
[2022-10-17 12:21:18.535] [INFO] [org.burningokr.service.configuration.ConfigurationService] - Updated OAuth Configuration
[2022-10-17 12:21:18.573] [INFO] [org.burningokr.service.cycle.CycleService] - {0}: Application startup detected, processing automatic cycle switch if necessary.
[2022-10-17 12:21:18.582] [INFO] [org.burningokr.service.userutil.AadUserListUpdater] - Updating user database...
[2022-10-17 12:21:19.648] [ERROR] [org.springframework.boot.SpringApplication] - Application run failed
java.lang.IllegalStateException: STATE 403
        at org.burningokr.service.userutil.AzureApiCaller.callApi(AzureApiCaller.java:46) ~[burning-okr-logic.jar!/:?]
        at org.burningokr.service.userutil.AzureUserFetcher.fetchAzureUsersForGroupId(AzureUserFetcher.java:68) ~[burning-okr-logic.jar!/:?]
        at org.burningokr.service.userutil.AzureUserFetcher.fetchAzureUsers(AzureUserFetcher.java:57) ~[burning-okr-logic.jar!/:?]
        at org.burningokr.service.userutil.AadUserListUpdater.updateAadUserList(AadUserListUpdater.java:57) ~[burning-okr-logic.jar!/:?]
        at org.burningokr.service.userhandling.AadUserService.updateUsers(AadUserService.java:94) ~[burning-okr-logic.jar!/:?]
        at org.burningokr.service.userhandling.AadUserService.updateUsersAtStartup(AadUserService.java:88) ~[burning-okr-logic.jar!/:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_342]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_342]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_342]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_342]
        at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:261) ~[spring-context-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
        at org.springframework.context.event.ApplicationListenerMethodAdapter.processEvent(ApplicationListenerMethodAdapter.java:180) ~[spring-context-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
        at org.springframework.context.event.ApplicationListenerMethodAdapter.onApplicationEvent(ApplicationListenerMethodAdapter.java:142) ~[spring-context-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172) ~[spring-context-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165) ~[spring-context-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139) ~[spring-context-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:400) ~[spring-context-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:354) ~[spring-context-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
        at org.springframework.boot.context.event.EventPublishingRunListener.running(EventPublishingRunListener.java:103) ~[spring-boot-2.0.4.RELEASE.jar!/:2.0.4.RELEASE]
        at org.springframework.boot.SpringApplicationRunListeners.running(SpringApplicationRunListeners.java:78) ~[spring-boot-2.0.4.RELEASE.jar!/:2.0.4.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:346) [spring-boot-2.0.4.RELEASE.jar!/:2.0.4.RELEASE]
        at org.burningokr.BurningOkrApp.main(BurningOkrApp.java:33) [classes!/:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_342]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_342]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_342]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_342]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [burning-okr.jar:?]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [burning-okr.jar:?]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [burning-okr.jar:?]
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51) [burning-okr.jar:?]
```

**Expected behavior**
Login to Application with Azure AD Login

**backend.env**
```
# The Authentication Mode.
# Use "local" to use the local database for the user management.
# Use "azure" to use an Azure Active Directory with OAuth for the user management.
SYSTEM_CONFIGURATION_AUTH_MODE=azure

# The following settings are only for the authentication with the Azure Active Directory.
# You do not need to change anything in the following settings, when you are using the local Authentication Mode.
#
# Azure Ad Issuer
AZURE_AD_ISSUER=https://login.microsoftonline.com/<my-azure-ad-tennant-id>/v2.0

# The Azure Ad ClientId
SECURITY_OAUTH2_CLIENT_CLIENTID=<client-id>

# The Azure Ad Client secret
SECURITY_OAUTH2_CLIENT_CLIENTSECRET=<client-secret>

# The Azure Ad Access Token URI
SECURITY_OAUTH2_CLIENT_ACCESSTOKENURI=https://login.microsoftonline.com/<my-azure-ad-tennant-id>/oauth2/v2.0/token

# The Azure Ad User Authorization URI
SECURITY_OAUTH2_CLIENT_USERAUTHORIZATIONURI=https://login.microsoftonline.com/<my-azure-ad-tennant-id>/oauth2/v2.0/authorize

# The Azure Ad User Info URI (e.g. https://graph.microsoft.com/v1.0/me/)
SECURITY_OAUTH2_RESOURCE_USERINFOURI=https://graph.microsoft.com

# The Azure Active Directory groups, that are authorized to use BurningOKR.
# You can add as many groups as you like.
# You must specify at least one group.
AZURE_AD_AZUREGROUPS_0_NAME=BurningOKR-All-Test
AZURE_AD_AZUREGROUPS_0_ID=<group-id>
```

I also took a look at the issue https://github.com/BurningOKR/BurningOKR/issues/121 but couldn't figure how to make correct settings.

I copied the urls from the issues mentioned above and put in my azure ad tennant id. I also understand the Azure AD group stuff. But I'm unsure about the SECURITY_OAUTH2_CLIENT_CLIENTID and SECURITY_OAUTH2_CLIENT_CLIENTSECRET. Do I have to create a "normal" Application in Azure AD or an Enterprise Application?

If someone could explain this to me and I get this to work I would extend the README with more information about that and make a PR for this.

**Comment by Michael-List** [comment]
Hi @MeepMr can you help me with this topic?

**Comment by amentler** [comment]
Hey Michael,

a few of us have looked at your problem but we dont really know what might have happened, except that the configuration is still wrong which the 403 is indicating

our burning okr team is currently paused and working on another open source project.
i asked our internal maintenance team if they could provide some information about the format of the different settings and if they could answer your question regarding "Do I have to create a "normal" Application in Azure AD or an Enterprise Application". im waiting for their reply.

**Comment by amentler** [comment]
ok we have burningokr deployed as an enterprise application

**Comment by amentler** [comment]
if i understood correctly when i talked to our maintenance guy the client id is the application id.
the secret you can find or create somwhere in the azure application. it doesnt have a fixed format that i could tell you to identify it easier.

**Comment by Michael-List** [comment]
Hi thanks for your help but im still getting an error 403. I will use local authentication.
